@api = http://localhost:5000/api

### POST
POST {{api}}/classes
Content-Type: application/json

{
    "name": "8A",
    "teacherId": "0b74d281-4fd4-471b-b066-886dd2ffc0c5",
    "subjects": [
        "cde1608f-42ee-49f2-ac0b-97ca4bda653f",
        "703dae29-b840-4147-a6b4-ff7afcba513b",
        "da36c392-2b9b-4405-9daa-aaae71521fe6",
        "f1305d39-1184-46ba-a514-6631fb0ad736",
        "ec2f116b-a1ac-4505-add8-f67bd0927034",
        "703dae29-b840-4147-a6b4-ff7afcba513b",
        "1acc52f3-de0e-4bad-820a-d0a915729ea5"
    ]
}

### GET
GET {{api}}/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyMDAxYzMwYS1iMTQ1LTQ0N2UtYjAzZS1kZjY1MTdmNGQ2MTciLCJpYXQiOjE3MTE0NTI2NjEsImV4cCI6MTcxMTQ3NDI2MX0.ZQWdPSEDQy0dt72P7APuzBokmv--BqW8LU5_RqsGvdA

### GET NR_OF_STUDENTS
GET {{api}}/classes/nrOfStudents

### GET Teachers
GET {{api}}/classes/f8642a8f-b985-443d-bcfe-ee63070c4261/teachers

### PUT
PUT {{api}}/classes/3d9bc254-e757-400b-b867-171886469a22
Content-Type: application/json

{
    "teacherId": "026430d7-a3e2-423e-9417-59aea9f3cc2a"
}

### DELETE
DELETE {{api}}/classes/d32fefb9-5a71-4052-95ab-0ff137c94aab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyMDAxYzMwYS1iMTQ1LTQ0N2UtYjAzZS1kZjY1MTdmNGQ2MTciLCJpYXQiOjE3MTE0NTI2NjEsImV4cCI6MTcxMTQ3NDI2MX0.ZQWdPSEDQy0dt72P7APuzBokmv--BqW8LU5_RqsGvdA


