@api = http://localhost:5000/api

### POST
POST {{api}}/schedules
Content-Type: application/json

{
    "classId": "8ac5a125-8065-4e58-ba1b-534a5028936b"
}

### GET
GET {{api}}/schedules

### GET
GET {{api}}/schedules/teachers/026430d7-a3e2-423e-9417-59aea9f3cc2a

### PUT
PUT {{api}}/schedules/564d5bcc-4e0f-4a16-9428-ecc0708ec3ad
Content-Type: application/json

{
    "subjects": []
}

### DELETE
DELETE {{api}}/schedules/617be495-38d1-49e8-955d-32cba877dd64

