@api = http://localhost:5000/api

### GET 
GET {{api}}/students

### POST
POST {{api}}/students
Content-Type: application/json

{
    "userId": "16f642dc-5a48-455b-9bdb-90ec967362b0",
    "classId": "26fd33c4-e8a3-4c24-8f75-434e3cbc39eb"
}

### PUT
PUT {{api}}/students/6f8174ee-4b88-4298-8d3e-aae2ca5efba4
Content-Type: application/json

{
    "grades": []
}

### DELETE
DELETE {{api}}/students/ae4d7fc6-f758-477d-b80d-3a2015a5a0cf