@api = http://localhost:5000/api

### GET 
GET {{api}}/students

### POST
POST {{api}}/students
Content-Type: application/json

{
    "userId": "6ac53401-9a77-471c-96d1-e051d44f7ae4",
    "classId": "8ac5a125-8065-4e58-ba1b-534a5028936b"
}

### PUT
PUT {{api}}/students/6f8174ee-4b88-4298-8d3e-aae2ca5efba4
Content-Type: application/json

{
    "grades": []
}

### DELETE
DELETE {{api}}/students/1fae63c7-244d-4155-9cfa-efdb3a84f700