@api = http://localhost:5000/api

### POST
POST {{api}}/teachers
Content-Type: application/json

{
    "userId": "b5547102-6ad6-42a4-989f-729406c6562a",
    "subjectId": "1acc52f3-de0e-4bad-820a-d0a915729ea5"
}

### PUT
PUT {{api}}/teachers/77f2b927-401a-456b-b4a9-289f0d5b1c87
Content-Type: application/json

{
    "classes": []
}

### GET
GET {{api}}/teachers

### DELETE
DELETE {{api}}/teachers/55b01d35-7179-444c-a4a5-8b74127f0a13
Content-Type: application/json