@api = http://localhost:5000/api

### POST
POST {{api}}/teachers
Content-Type: application/json

{
    "userId": "e21205d4-8d96-4866-95d9-04bf521ae89f",
    "subjectId": "e726e4a0-f0e4-4c1f-acfd-60c8748a90f0"
}

### PUT
PUT {{api}}/teachers/3a197924-f9df-41bd-afbd-dc4cb36fc0e1
Content-Type: application/json

{
    "classes": ["26fd33c4-e8a3-4c24-8f75-434e3cbc39eb", "606ca4d8-30ec-4ce2-b0d2-db400f58c693"]
}

### GET
GET {{api}}/teachers

### DELETE
DELETE {{api}}/teachers/55b01d35-7179-444c-a4a5-8b74127f0a13
Content-Type: application/json