@api = http://localhost:5000/api

### POST
POST {{api}}/users/login/vlad
Content-Type: application/json

{
    "password": "123456"
}

### POST
POST {{api}}/users/signUp
Content-Type: application/json

{
    "firstName": "admin",
    "lastName": "admin",
    "cnp": "1234567891234",
    "email": "adminCN@gmail.com",
    "password": "admin",
    "phoneNumber": "0732345678"
}

### POST Population
POST {{api}}/users/population
Content-Type: application/json

### PUT
PUT {{api}}/users/7b088758-6c1b-49fb-9230-e90738022c02
Content-Type: application/json

{
    "role": "director"
}

### GET
GET {{api}}/users

### POST
POST {{api}}/users/population

### DELETE ALL
DELETE {{api}}/users

### GET user by email
GET {{api}}/users/dragos.ionescu@gmail.com

### PUT director
PUT {{api}}/users/director/253dcfca-48e6-4b4d-b5c2-f791b3b7eb7a

### GET director
GET {{api}}/users/director

